name: creating infra
on:
  push:
    branches:
      - 'dev'
      - 'int'
      - 'prod'
    paths:
     - 'Development/**'
     - 'Integration/**'
     - 'Production/**'
jobs:
  dev-infra:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: Development
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: authenticate with gcp
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDS }}'
      - name: set up gcloud
        uses: 'google-github-actions/setup-gcloud@v2'
      - name: initializing terraform
        run: 'terraform init'
      - name: syntax validation
        run: 'terraform validate'
      - name: applying terraform changes
        run: 'terraform apply --auto-approve'
  int-infra:
    if: github.ref == 'refs/heads/int'
    runs-on: ubuntu-latest
    environment: int
    defaults:
      run:
        working-directory: Integration
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: authenticate with gcp
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDS }}'
      - name: set up gcloud
        uses: 'google-github-actions/setup-gcloud@v2'
      - name: initializing terraform
        run: 'terraform init'
      - name: syntax validation
        run: 'terraform validate'
      - name: applying terraform changes
        run: 'terraform apply --auto-approve'
  prod-infra:
    if: github.ref == 'refs/heads/prod'
    runs-on: ubuntu-latest
    environment: prod
    defaults:
      run:
        working-directory: Production
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: authenticate with gcp
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDS }}'
      - name: set up gcloud
        uses: 'google-github-actions/setup-gcloud@v2'
      - name: initializing terraform
        run: 'terraform init'
      - name: syntax validation
        run: 'terraform validate'
      - name: applying terraform changes
        run: 'terraform apply --auto-approve'